# Site settings
title: Magic World
email: malibo8407@gmail.com 
description: "Try it one more time on the Magic World is the only way to make wounderful thing. And it is the same thing about life. Simplicity is most complexity. Think more, Talk less, and Try it one more time. Welcome to my Magic World"
baseurl: ""
url: "http://liboma.gihub.io"

# Build settings
markdown: kramdown
permalink: pretty
